name: Clean up mainfest

on:
  workflow_dispatch:

jobs:
  update-plugins:
    runs-on: ubuntu-latest
    name: Update plugins
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
          ref: ${{ github.head_ref }}
      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ github.token }}
      - name: Clean up manifest.txt
        uses: NixNeovim/NixNeovimPlugins/.github/actions/cleanup@main
      - name: Commit changes
        uses: NixNeovim/NixNeovimPlugins/.github/actions/ci-commit@main
        with:
          msg: 'Update plugins'
